name: TeamPlugin
version: 1.0.0
main: io.papermc.teamplugin.Main
description: Simple team plugin
author: pairnon
website: https://github.com/pairnon/TeamPlugin
api-version: '1.20'
commands:
  createteam:
    description: Create a team with a specified name
    usage: createteam <name>
  listteams:
    description: Get a list of all teams
    usage: listteams
  jointeam:
    description: Join a team
    usage: jointeam <name>
  leaveteam:
    description: Leave your team
    usage: leaveteam